(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/HTML5rastershad.png?1504305104156", id:"HTML5rastershad"},
		{src:"images/Payback160x600.jpg?1504305104156", id:"Payback160x600"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Payback160x600 = function() {
	this.initialize(img.Payback160x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,210);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.parent = this;
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPARIAAghIAfAAIAAAhg");
	this.shape.setTransform(24.6,101.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBXQgLgEgJgJQgIgJgFgMIgFgOIgBgQIAAAAQAAgLAGgQQAEgNAJgJQAJgIALgFQAKgFAMAAQAGAAAIACQAGACAFAEQALAFAHALIAAhHIAfAAIAAC0IgfAAIAAgWQgHAMgLAGIgLAFQgIACgGAAQgLAAgLgFgAgNgOQgHADgFAFQgFAGgDAFQgEAIABAKIAAAAQgBAKAEAIQADAHAFAGQAFAGAHADQAHADAGAAQAHAAAHgDQAHgDAGgGQAFgGADgHQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_1.setTransform(12.5,94);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeBBQgIgDgHgFQgGgFgEgHQgDgJAAgJIAAAAQAAgLADgIQAFgIAHgEQAHgGAJgCQAKgDAMAAQAOAAAVAFIAAgCQAAgGgCgGQgDgFgEgDQgEgEgGgCQgGgCgGAAQgLAAgJACQgIACgKAEIgIgYQAMgGALgCQANgDANAAQAOAAALAEQAKADAIAIQAHAHAEAKQADALAAANIAABMIgeAAIAAgQQgHAIgKAGQgNAFgLAAQgJAAgJgDgAgLAGQgGABgEADQgEADgCAEQgCADAAAFIAAABQABAIAHAGQAHAFALAAQAGAAAGgCQAGgCAFgDQAFgEADgFQACgFAAgGIAAgIQgTgGgLAAQgFABgGABg");
	this.shape_2.setTransform(-3.2,96.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHBaQgGgCgGgDQgKgGgIgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_3.setTransform(-18.2,94);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBDIgOgEQgMgFgKgJQgJgKgGgNIgDgMIgCgOIAAAAQAAgIAFgRQAGgMAJgKQAKgJAMgGIAOgEIANgCQAKAAASAGQAMAGAKAJQAJAJAGAMQAFASAAAIIAAAAIgCAOIgDAMQgGAMgJAKQgKAKgMAFQgTAFgJABgAgPglQgHACgGAHQgFAFgDAIQgDAHAAAIIAAAAQAAAIADAIQADAIAGAFQAFAHAIADQAHADAHABQAJgBAHgDQAIgDAFgHQAFgFADgIQACgIAAgIIAAAAQAAgHgCgIQgDgHgFgGQgGgGgIgDQgHgEgIAAQgHAAgIAEg");
	this.shape_4.setTransform(36.1,69.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgGIANgVQAKAHAMAFQALAEAJAAQAJAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgFgDgNgFQgVgGgHgEQgHgEgDgGQgDgHgBgJIAAgBQABgJADgIQADgGAHgGQAHgFAIgDQAJgDAHAAQAMAAANAEQANAEALAHIgMAWQgKgGgKgDQgJgEgIAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAOAEIAOAGQAGAFADAGQAEAGAAAJIAAAAQAAALgEAHQgEAJgGAFQgHAFgJACQgJADgKAAQgMAAgPgFg");
	this.shape_5.setTransform(21.5,69.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJAAgEgDg");
	this.shape_6.setTransform(2.6,67.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTAWQALgDAFgFQAEgGgBgIIgLAAIAAgiIAfAAIAAAdQAAAJgCAHQgDAIgFAEQgEAFgGAEQgHACgJABg");
	this.shape_7.setTransform(-6,62.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdBDIAAhJQAAgHgCgHQgCgFgEgFQgEgEgFgCQgFgCgHgBQgEABgGACQgFACgEAFQgEAEgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAVQAIgLAJgGIALgFQAEgCAIAAQALAAAJAEQAIAEAGAGQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_8.setTransform(-16.8,69.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgGIANgVQAKAHAMAFQALAEAIAAQAKAAAGgEQAFgDAAgIIAAAAQAAgHgJgEQgFgDgOgFQgUgGgHgEQgHgEgDgGQgEgHAAgJIAAgBQAAgJAEgIQAEgGAGgGQAGgFAJgDQAJgDAIAAQALAAANAEQANAEAKAHIgLAWQgKgGgJgDQgLgEgHAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAOAEIAOAGQAGAFADAGQAEAGAAAJIAAAAQAAALgEAHQgEAJgGAFQgHAFgJACQgJADgKAAQgNAAgOgFg");
	this.shape_9.setTransform(-31,69.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_10.setTransform(-40.7,67);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAaBbIgmg5IgSATIAAAmIgeAAIAAi1IAeAAIAABrIA1g4IAkAAIg0A0IA2BOg");
	this.shape_11.setTransform(46.8,39.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgFBDIgOgEQgMgFgJgJQgJgKgFgNQgGgMAAgOIAAAAQAAgMAGgNQAFgMAJgKQAJgJANgGIANgEIAMgCQAJABAIACQAIABAGADQAJAEANAMIgTAUQgIgHgHgEQgJgFgKAAQgHAAgGAEQgHADgGAGQgFAFgCAIQgDAHAAAIIAAAAQAAAIADAIQACAIAGAGQAFAFAHAEQAGADAIABQAKAAAJgGQAIgDAHgIIATASQgOANgIAEQgHAEgIACQgIACgJAAg");
	this.shape_12.setTransform(31.7,42.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeBBQgIgDgGgFQgHgFgEgHQgEgJABgJIAAAAQgBgLAEgIQAFgIAHgEQAHgGAKgCQAKgDALAAQAOAAAUAFIAAgCQABgGgCgGQgCgFgFgDQgEgEgGgCQgGgCgGAAQgLAAgJACQgIACgKAEIgIgYQAMgGALgCQANgDANAAQANAAAMAEQALADAHAIQAHAHAEAKQADALAAANIAABMIgeAAIAAgQQgHAIgKAGQgOAFgKAAQgJAAgJgDgAgLAGQgFABgFADQgDADgCAEQgDADAAAFIAAABQAAAIAIAGQAHAFALAAQAGAAAGgCQAHgCAEgDQAFgEADgFQACgFAAgGIAAgIQgTgGgLAAQgGABgFABg");
	this.shape_13.setTransform(16.8,42.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgHBaQgGgCgGgDQgKgGgIgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_14.setTransform(1.8,40);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgsBTQgHgCgHgDIAKgXQAJAFAJABQAGAAAFgEQAEgDAEgJIg3iCIAgAAIAkBgIAihgIAfAAIg0CGIgIARQgFAHgDAFQgFAEgGACQgHACgIAAQgJAAgIgDg");
	this.shape_15.setTransform(-14.4,44.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgdBBQgJgDgHgFQgGgFgEgHQgDgJAAgJIAAAAQAAgLADgIQAEgIAIgEQAGgGAKgCQALgDALAAQAOAAAVAFIAAgCQgBgGgCgGQgCgFgEgDQgEgEgGgCQgGgCgGAAQgKAAgKACQgIACgJAEIgJgYQAMgGAKgCQANgDANAAQAOAAAMAEQALADAHAIQAHAHADAKQAFALAAANIAABMIgfAAIAAgQQgHAIgKAGQgNAFgKAAQgKAAgIgDgAgLAGQgFABgEADQgFADgCAEQgBADAAAFIAAABQAAAIAHAGQAHAFALAAQAFAAAHgCQAGgCAFgDQAFgEACgFQADgFAAgGIAAgIQgSgGgMAAQgFABgGABg");
	this.shape_16.setTransform(-29.5,42.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhDBXIAAiqIAeAAIAAAWQAJgMAKgFQAFgEAHgCQAGgCAGAAQAMAAALAFQALAEAJAJQAJAJAFAMQAFATAAALIAAAAIgCAPIgDANQgFAMgJAJQgJAIgLAFQgLAFgMAAQgGAAgHgCQgGgCgGgEQgKgFgIgKIAAA8gAgNg5QgHADgGAGQgFAGgDAIQgDAHAAAKIAAAAQAAAKADAHQADAGAFAGQAGAGAHACQAHADAGAAQAHAAAHgDQAHgCAFgGQAFgFADgHQADgIAAgJIAAAAQAAgKgDgHQgDgJgFgFQgFgGgHgDQgHgCgHAAQgGAAgHACg");
	this.shape_17.setTransform(-44.5,44.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgTAWQALgDAGgFQADgGgBgIIgLAAIAAgiIAfAAIAAAeQAAAIgDAHQgBAIgGAEQgEAGgGACQgHADgKABg");
	this.shape_18.setTransform(51.4,22.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgsBTQgHgBgHgEIAKgXQAJAFAJABQAGAAAFgEQAEgDAEgJIg3iCIAgAAIAkBgIAihgIAfAAIg0CGIgIARQgFAHgDAFQgFAEgGACQgHACgIAAQgJAAgIgDg");
	this.shape_19.setTransform(41,17.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNBbIAAi1IAcAAIAAC1g");
	this.shape_20.setTransform(30,12.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgOBbIAAi1IAdAAIAAC1g");
	this.shape_21.setTransform(22.9,12.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeBBQgIgDgGgFQgHgFgDgHQgFgJAAgJIAAAAQAAgLAFgIQAEgIAHgEQAHgGAKgCQAKgDALAAQAOAAAUAFIAAgCQAAgGgCgGQgCgFgEgDQgEgEgGgCQgGgCgGAAQgKAAgKACQgIACgKAEIgIgYQAMgGAKgCQAOgDAMAAQAPAAALAEQALADAHAIQAHAHADAKQAEALABANIAABMIgfAAIAAgQQgHAIgKAGQgNAFgLAAQgJAAgJgDgAgLAGIgKAEQgEADgBAEQgCADAAAFIAAABQgBAIAIAGQAHAFALAAQAFAAAHgCQAGgCAFgDQAFgEACgFQADgFAAgGIAAgIQgTgGgLAAQgGABgFABg");
	this.shape_22.setTransform(11.6,15.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgfA/QgIgDgGgHQgGgGgEgKQgDgJAAgMIAAhSIAeAAIAABJQAAAIACAFQACAGAEAFQADAEAGACQAFACAGAAQAFAAAGgCQAFgCAEgFQAEgDACgHQACgGAAgHIAAhJIAfAAIAACCIgfAAIAAgUQgHAKgJAGIgLAFQgEACgIAAQgLAAgJgEg");
	this.shape_23.setTransform(-3.2,15.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJAAgEgDg");
	this.shape_24.setTransform(-16.2,13.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgFBDIgOgEQgMgFgJgJQgJgKgFgNQgGgMAAgOIAAAAQAAgMAGgNQAFgMAJgKQAJgJANgGIANgEIAMgCQAJABAIACQAIABAGADQAJAEANANIgTATQgIgHgHgEQgJgFgKAAQgHAAgGAEQgHADgGAGQgFAFgCAIQgDAHAAAIIAAAAQAAAIADAJQACAHAGAGQAFAFAHAEQAGADAIABQAKAAAJgGQAIgDAHgJIATATQgOANgIAFQgHADgIACQgIACgJAAg");
	this.shape_25.setTransform(-28.1,15.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA6BYIgRgqIhRAAIgSAqIggAAIBNivIAbAAIBNCvgAAdASIgdhEIgdBEIA6AAg");
	this.shape_26.setTransform(-45.3,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.5,0,165,110);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("EgMfAsOMAAAhYbIY/AAMAAABYbg");
	this.shape.setTransform(80,262,1,0.926);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape.setTransform(40.4,94.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgOArQgJgDgFgHQgHgGgDgIIgDgJIgBgKIAAAAQAAgIADgJQADgIAHgHQAFgGAIgEIAIgCIAIgBIAKABIAIADQAGACAIAIQAGAHACAIQADAJAAAIIgBAGIg/AAIACAJQADAFAEADIAHAEQAEABAEAAQAHAAAFgCQAGgDAFgFIANAKIgHAHQgEAEgEACIgKADIgMABQgHAAgJgDgAAXgFQgBgFgCgEQgCgFgDgDIgGgFQgFgCgEAAQgDAAgEACQgEACgDADIgFAHQgCAFAAAFIAsAAIAAAAg");
	this.shape_1.setTransform(33.1,91.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgQArQgNgGgFgEIAJgOQAHAFAIADQAHADAFAAQAHAAAEgDQADgCAAgFQAAgFgGgDIgMgFQgNgEgGgDQgEgCgCgEQgDgFAAgGIAAgBQAAgFADgGQACgFAFgDQAEgEAGgCQAGgCAEAAQAJAAAIADQAJADAHAEIgIAPQgHgEgGgCQgHgDgFABQgEgBgEADQgDADAAAEIAAAAQAAAEAGAEIAMAEIAKAEIAJADQAFADACAEQACAFAAAFIAAABQAAAHgCAGQgDAFgEADQgFADgGACQgGACgHAAQgIAAgKgDg");
	this.shape_2.setTransform(23.5,91.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgUAsQgFgCgFgDQgEgEgCgFQgDgGAAgGQAAgIADgFQACgFAFgDQAFgDAHgCQAGgBAIAAQAJAAAOADIAAgBQAAgFgBgEIgFgGIgGgDQgFgCgDAAQgHAAgHACQgFABgGADIgHgRQAJgEAHgBQAJgCAIAAQAKAAAHADQAIACAEAFQAFAFADAHQACAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgJAEgGAAQgGAAgHgCgAgHAEQgEAAgDADIgDAEQgCADAAADQAAAHAFADQAFAEAHgBQAEABAEgCQAEgCADgCQAEgCACgEQABgEAAgEIAAgEQgMgEgIAAIgHABg");
	this.shape_3.setTransform(14.2,91.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AATA9IAAgyQAAgGgBgEQgBgCgDgCQgCgDgEgCQgDgBgFgBIgGACQgEACgDADIgEAFQgBAEAAAFIAAAyIgVAAIAAh6IAVAAIAAAxQAFgIAGgDIAHgEIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAHIAAA4g");
	this.shape_4.setTransform(4.3,89.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgEAtIgIgCQgJgEgGgGQgGgHgEgIQgDgJAAgJQAAgIADgJQAEgIAGgGQAGgHAJgEIAJgCIAHgBIAMABIAKADQAFADAJAIIgMAOQgGgGgEgCQgGgDgIAAQgEAAgEACQgEACgEAEQgDAEgDAFQgCAFAAAFIAAAAQAAAFACAGQADAFADAEQAEAEAEACQAEACAFAAQAHAAAHgDQAEgCAGgGIAMAMQgJAKgGADIgKADIgMABg");
	this.shape_5.setTransform(-5.8,91.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgZAtIAAhXIAVAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAFAAIAAAWIAAAAQgHAAgGACQgFACgFAEQgCAFgBAHQgDAEAAAJIAAAig");
	this.shape_6.setTransform(-13.8,91);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBIAGgEQADgDACgEQABgFAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_7.setTransform(-23,91.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgtA7IAAhzIAUAAIAAAPQAGgIAHgEIAIgEIAIgBQAIAAAHADQAIADAGAGQAGAGADAJQAEAMAAAIIAAAAIgBALIgDAHQgDAIgGAGQgGAGgIAEQgHADgIAAQgEAAgEgCQgEgBgEgCQgHgEgGgHIAAApgAgJgmQgEACgEAEQgEAEgCAFQgCAFAAAHIAAAAQAAAGACAFQACAEAEAEQAEAEAEACQAFACAEAAQAEAAAFgCQAFgCADgEQAEgEACgEQACgFAAgGIAAAAQAAgHgCgFQgCgFgEgEQgEgEgEgCQgFgCgEAAQgEAAgFACg");
	this.shape_8.setTransform(-33.6,92.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgdA4QgFAAgFgDIAHgPQAGADAGAAQAEAAAEgCQADgDACgGIgmhXIAXAAIAXBBIAXhBIAVAAIgjBaIgFAMQgDAEgCAEQgEACgEACIgKABQgGAAgFgCg");
	this.shape_9.setTransform(32.2,73.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgYAtIAAhXIAUAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgCAAQgGAAgGACQgGACgEAEQgCAFgCAHQgCAEAAAJIAAAig");
	this.shape_10.setTransform(24,72);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIgBAGIhAAAIADAJQADAFADADIAIAEQAFABADAAQAHAAAFgCQAGgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgHAAgJgDgAAWgFQAAgFgCgEQgBgFgEgDIgGgFQgEgCgFAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_11.setTransform(15,72.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AgIAtIglhYIAXAAIAWA/IAYg/IAVAAIgkBYg");
	this.shape_12.setTransform(4.8,72.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAJgCIAHgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIgBAGIhAAAIADAJQADAFADADIAIAEQAFABADAAQAGAAAGgCQAGgDAGgFIAMAKIgHAHQgEAEgFACIgKADIgLABQgHAAgJgDgAAWgFQAAgFgCgEQgBgFgEgDIgGgFQgEgCgFAAQgDAAgEACQgEACgDADIgFAHQgCAFgBAFIAsAAIAAAAg");
	this.shape_13.setTransform(-5.3,72.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_14.setTransform(-20.8,72);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_15.setTransform(-31.7,72.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAYA6QgFgCgEgEQgEgEgCgGQgBgFAAgHIAAAAQAAgGABgGQACgGAFgDQADgEAGgDQAEgCAHAAQAGAAAFACQAFACAEAFQAEADACAGQABAGAAAFIAAABQAAAGgBAGQgCAFgEAFQgEAEgFACQgGADgFAAQgGAAgGgDgAAaASQgDAFAAAGIAAABQAAAHADAFQAEAGAGgBQAFABAEgGQADgEAAgIIAAAAQAAgIgDgEQgEgFgFgBQgGABgEAFgAgyA7IBVh1IARAAIhWB1gAgugBQgFgCgDgEQgFgEgCgGQgBgFAAgGIAAgBQAAgGABgGQACgFAFgFQADgDAGgDQAEgCAHgBQAGABAFACQAGADADADQAEAEACAGQACAGgBAGQABAGgCAGQgDAGgDAEQgEAEgFACQgGABgGAAQgFAAgGgBgAgsgpQgDAEAAAIQAAAIAEAFQADAEAGAAQAFAAAEgEQADgFAAgHIAAgBQAAgHgDgFQgEgFgGAAQgFAAgEAFg");
	this.shape_16.setTransform(32.9,51.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgLA7IgMgEIgKgFIgJgIIANgPQAHAGAHAEQAIAEAHAAQAFAAAEgCIAHgEQAEgCABgEQACgEAAgFIAAAAQAAgFgCgDIgFgGQgDgDgFgCIgIgBIgMACIgKAEIgMgGIADg7IBFAAIAAASIgzAAIgCAcIAJgCIAIgBQAJAAAHACQAIACAGAFQAFAFADAFQADAHAAAJQAAAKgDAHQgDAIgGAFQgGAFgIADQgIADgJAAQgFAAgGgBg");
	this.shape_17.setTransform(20.3,51.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape_18.setTransform(12.8,56.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AACA7IAAhgIgTAGIgFgRIAegKIAPAAIAAB1g");
	this.shape_19.setTransform(6.6,51.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_20.setTransform(-6.4,53);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgZAtIAAhXIAVAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgBAAQgHAAgGACQgGACgEAEQgCAFgBAHQgDAEAAAJIAAAig");
	this.shape_21.setTransform(-14.8,53);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgTAsQgGgBgFgEQgEgEgCgFQgDgFAAgHQAAgHADgGQACgFAFgDQAFgDAHgCQAGgCAIAAQAJAAAOAEIAAgBQAAgFgCgEIgDgGIgHgDQgFgCgDAAQgHAAgHACQgFABgGADIgHgRQAJgEAHgBQAJgCAIAAQAJAAAIADQAIACAEAFQAFAEADAIQACAGAAAKIAAAzIgUAAIAAgLQgFAGgHADQgIAEgHAAQgGAAgGgCgAgHAEQgEABgDABIgDAFQgCADAAADQAAAGAFAEQAFADAIABQADgBAEgBQAEgCADgCQAEgDABgDQACgEAAgDIAAgGQgMgDgIAAIgHABg");
	this.shape_22.setTransform(-23.9,53.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgrA7IAAh1IBWAAIAAASIhCAAIAAAgIA7AAIAAARIg7AAIAAAfIBDAAIAAATg");
	this.shape_23.setTransform(-34,51.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgKALIAAgVIAVAAIAAAVg");
	this.shape_24.setTransform(21.9,31.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgTA7QgHgDgGgGQgGgGgDgJIgDgJIgBgKIAAgBQAAgHAEgKQADgJAGgGQAGgGAHgDQAIgDAIAAIAIABIAIAEQAHADAFAIIAAgxIAVAAIAAB6IgVAAIAAgOQgFAIgHAEQgEACgEABQgFABgDAAQgIAAgIgDgAgIgKQgFADgEAEQgDADgCAEQgCAFAAAGIAAABQAAAGACAGQACAFAEAEQADAEAFABQAEACAEAAQAFAAAEgCQAFgBAEgEQAEgFACgEQACgGAAgGIAAgBQAAgGgCgFQgCgEgEgDQgEgEgFgCQgEgCgFgBQgEAAgEACg");
	this.shape_25.setTransform(13.8,26.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgYAtIAAhXIAUAAIAAAUIAEgJQACgFAEgCQAEgEAFgBQAFgBAGAAIAAAWIgBAAQgHAAgGACQgGACgEAEQgCAFgCAHQgCAEAAAJIAAAig");
	this.shape_26.setTransform(5.2,28);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AgUAsQgFgCgFgDQgEgEgDgFQgCgGAAgGQAAgHACgGQADgFAFgDQAFgDAHgCQAGgBAIAAQAJAAAOADIAAgBQAAgFgBgEIgFgGIgGgDQgFgCgDAAQgHAAgHACQgFABgGADIgHgRQAJgEAHgBQAJgCAIAAQAKAAAHADQAIACAEAFQAFAFADAHQACAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgIAEgHAAQgGAAgHgCgAgHAEQgEAAgDADIgDAEQgCADAAADQAAAHAFADQAFAEAHgBQAEABAEgCQAEgCADgCQAEgCACgEQABgEAAgEIAAgEQgMgEgIAAIgHABg");
	this.shape_27.setTransform(-3.9,28.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgFA8IgLgEIgLgFIgIgIQgFgEgDgFIgGgKIgDgLIgBgNIAAAAIABgLIADgMIAGgKIAHgJIAJgIQAFgDAGgCIALgEIALgBQAJAAAGABQAHACAFACQAIAEAMAJIgOAQQgHgHgIgEIgIgDIgKgBQgGAAgHAEQgIACgFAHQgFAFgDAIQgDAHAAAIIAAAAQAAAIADAIQADAIAFAFQAFAHAIACQAHAEAGAAQAFAAAGgBIAIgEQAHgDAIgIIAOAOIgKAJIgLAGIgNAFQgHABgIAAIgKgBg");
	this.shape_28.setTransform(-14.7,26.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AARA9IgZgmIgMANIAAAZIgUAAIAAh6IAUAAIAABJIAjgmIAZAAIgjAiIAlA1g");
	this.shape_29.setTransform(39.8,7.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgDAtIgJgCQgIgEgHgGQgGgHgEgIQgDgJAAgJQAAgIADgJQAEgIAGgGQAHgHAIgEIAJgCIAIgBIALABIAKADQAFADAKAIIgOAOQgEgGgGgCQgGgDgGAAQgFAAgEACQgEACgEAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQADACAFAAQAIAAAFgDQAFgCAGgGIAMAMQgJAKgGADIgKADIgLABg");
	this.shape_30.setTransform(29.6,9.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgUAsQgFgBgFgEQgEgEgDgFQgCgFAAgHQAAgHACgGQADgFAFgDQAFgDAGgCQAHgCAIAAQAJAAAOAEIAAgBQAAgFgBgEIgFgGIgHgDQgEgCgDAAQgHAAgGACQgGABgGADIgGgRQAIgEAHgBQAIgCAJAAQAKAAAHADQAIACAFAFQAEAEADAIQACAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgIAEgHAAQgGAAgHgCgAgHAEQgDABgDABIgFAFQgBADAAADQAAAHAFADQAFADAHAAQADABAFgCQAEgCADgCQAEgCACgEQACgEAAgEIAAgFQgNgDgIAAIgHABg");
	this.shape_31.setTransform(19.4,9.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgwA7IAAh1IAzAAQALAAAHADQAIACAGAGQADADACAGQACAEAAAHIgBAJIgEAIQgEAFgHAEIAJACQAEADAEAEQADADABAFQACAEAAAGIAAAAQAAAIgDAHQgDAFgGAFQgGAEgIACQgIACgKAAgAgbApIAgAAIAKgCIAHgDQADgCACgDQABgDAAgEQAAgEgBgDQgCgDgDgCIgHgDIgMgBIgeAAgAgbgIIAbAAIAIgBQAFgBACgCQADgCABgDQACgDAAgEIAAgBQAAgDgBgDIgEgEQgDgCgEgBIgJgCIgbAAg");
	this.shape_32.setTransform(8.9,7.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F78E1E").s().p("AATA9IAAgzQAAgFgBgEQgBgCgDgCQgCgEgEgBQgDgBgFgBIgGACQgEABgDAEIgEAEQgBAFAAAFIAAAyIgVAAIAAh6IAVAAIAAAxQAFgHAGgFIAHgDIAIgBQAHAAAGACQAGADAEAFQAEAEADAGQACAGAAAHIAAA4g");
	this.shape_33.setTransform(-7.9,7.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F78E1E").s().p("AgQArQgNgGgFgEIAJgOQAHAFAIADQAHADAFAAQAHAAAEgDQADgDAAgEQAAgFgGgDIgMgFQgNgEgGgDQgEgCgCgEQgDgFAAgGIAAgBQAAgFADgGQACgFAFgDQAEgEAGgCQAGgCAEAAQAJAAAIADQAJADAHAEIgIAPQgHgEgGgCQgHgDgFABQgEgBgEADQgDACAAAFIAAAAQAAAEAGAEIAMAEIAKAEIAJADQAFADACAEQACAFAAAFIAAABQAAAHgCAGQgDAFgEADQgFADgGACQgGACgHAAQgIAAgKgDg");
	this.shape_34.setTransform(-17.6,9.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F78E1E").s().p("AgTAsQgGgBgEgEQgFgEgCgFQgDgFAAgHQAAgHADgGQACgFAFgDQAFgDAGgCQAHgCAIAAQAJAAAOAEIAAgBQAAgFgCgEIgDgGIgIgDQgEgCgDAAQgHAAgHACQgFABgHADIgGgRQAJgEAHgBQAIgCAJAAQAJAAAIADQAHACAGAFQAFAEACAIQACAHAAAJIAAAzIgUAAIAAgLQgFAGgHADQgJAEgGAAQgHAAgFgCgAgHAEQgEABgDABIgEAFQgBADAAADQAAAHAFADQAFADAIAAQACABAFgCQAEgCAEgCQADgCABgEQACgEAAgEIAAgFQgMgDgIAAIgHABg");
	this.shape_35.setTransform(-26.9,9.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F78E1E").s().p("AgFA8IgMgEIgKgFIgJgIQgEgEgDgFIgFgKIgEgMIgBgMIAAAAIABgLIAEgMIAFgKIAHgJIAJgIQAFgDAFgCIAMgEIAMgBQAHAAAIABQAGABAGADQAHADAMAKIgNAQQgIgHgHgEIgJgDIgKgBQgGAAgIAEQgGACgGAHQgFAFgDAIQgDAHAAAIIAAAAQAAAIADAIQADAIAFAFQAGAHAGACQAIAEAGAAQAGAAAEgBIAJgEQAHgDAJgIIANAOIgKAIIgKAHIgOAFQgHABgHAAIgLgBg");
	this.shape_36.setTransform(-37.7,7.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F78E1E").s().p("AgTA8QgHgEgGgGQgGgGgDgJIgDgJIgBgKIAAgBQAAgHAEgKQADgJAGgGQAGgGAHgDQAIgDAIAAIAIABIAIADQAHAFAFAHIAAgxIAVAAIAAB6IgVAAIAAgPQgFAIgHAFQgEACgEABQgFACgDgBQgIAAgIgCgAgIgKQgFACgEAFQgDADgCAEQgCAFAAAGIAAABQAAAGACAFQACAGAEADQADAFAFABQAEACAEAAQAFAAAEgCQAFgBAEgFQAEgDACgGQACgFAAgGIAAgBQAAgGgCgFQgCgEgEgDQgEgEgFgCQgEgDgFABQgEAAgEABg");
	this.shape_37.setTransform(39.7,-11.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F78E1E").s().p("AATAtIAAgxQAAgFgBgEQgBgEgDgDQgCgDgEgBQgDgCgFAAIgGACQgEABgDADIgEAHQgBAEAAAGIAAAwIgVAAIAAhXIAVAAIAAANQAFgHAGgEIAHgDIAIgBQAHAAAGACQAGACAEAFQAEAFADAGQACAGAAAIIAAA3g");
	this.shape_38.setTransform(29.1,-10);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F78E1E").s().p("AgUArQgGgDgEgEQgFgFgCgGQgCgHAAgHIAAg3IAVAAIAAAwQAAAGABAEQABAEADADIAGAEQADABAEAAQADAAAEgBIAGgEQADgDACgEQABgFAAgFIAAgwIAVAAIAABXIgVAAIAAgOQgFAIgGADQgDADgEABQgDABgFAAQgHAAgGgCg");
	this.shape_39.setTransform(18.5,-9.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F78E1E").s().p("AgJAtIgJgCQgIgEgHgGQgGgHgEgIIgCgJIgBgJQAAgFADgMQAEgIAGgHQAHgGAJgEIAJgCIAIgBQAHAAAMADQAIAEAHAGQAGAHAEAIQADAMAAAFIAAAAIAAAJIgDAJQgEAIgGAGQgHAHgIAEQgNADgGAAgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFIAAAAQAAAFACAGQACAFAEAEQAEAEAFACQAFACAEAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgEgCgGQgCgFgEgEQgEgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_40.setTransform(7.7,-9.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F78E1E").s().p("AgJA8IgMgEIgNgGQgGgDgFgFIANgPQAGAEALAHIAKADIAJABIAIgBIAHgDIAEgEQABgEAAgDIAAgGIgFgEIgIgFIgMgDIgQgGQgIgDgEgBQgGgEgCgGQgDgGAAgIQAAgIADgGQADgHAGgEQAFgFAHgCQAIgCAIgBIALABQAGABAGACQAHADAMAIIgLAQQgJgGgHgDQgJgDgGAAIgIABIgGADQgFAEAAAGIAAABIABAFIAFAFIAIAEIAMAEIARAFQAHADAEACQAFAFADAFQACAGAAAHQAAAIgDAHQgDAGgFAGQgGAEgIACQgIADgJAAIgMgBg");
	this.shape_41.setTransform(-3.4,-11.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#F78E1E").s().p("AgOArQgIgDgHgHQgGgGgEgIIgCgJIgBgKIAAAAQAAgIADgJQAEgIAFgHQAGgGAIgEIAIgCIAIgBIAKABIAJADQAFACAIAIQAFAHADAIQADAJAAAIIgBAGIg/AAIACAJQADAFAEADIAHAEQAFABADAAQAGAAAGgCQAGgDAFgFIANAKIgHAHQgEAEgFACIgKADIgLABQgHAAgJgDgAAWgFQAAgFgCgEQgCgFgDgDIgGgFQgEgCgFAAQgDAAgEACQgEACgDADIgFAHQgCAFAAAFIArAAIAAAAg");
	this.shape_42.setTransform(-18.9,-9.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#F78E1E").s().p("AATA9IAAgzQAAgFgBgEQgBgCgDgCQgCgEgEgBQgDgCgFABIgGABQgEABgDAEIgEAEQgBAEAAAGIAAAyIgVAAIAAh6IAVAAIAAAxQAFgHAGgFIAHgDIAIgBQAHAAAGACQAGADAEAFQAEAEADAGQACAGAAAHIAAA4g");
	this.shape_43.setTransform(-29.3,-11.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#F78E1E").s().p("AgJA7IAAhiIgmAAIAAgTIBfAAIAAATIgmAAIAABig");
	this.shape_44.setTransform(-40.1,-11.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61,-21,122,122);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#794EA9").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Payback160x600();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// shad
	this.instance_1 = new lib.HTML5rastershad_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(168,220,1,1,0,0,0,0,10);
	this.instance_1.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,230);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201708_Payback_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_163 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(163).call(this.frame_163).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.parent = this;
	this.replay_btn.setTransform(7,7,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.parent = this;
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},164).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.parent = this;
	this.instance.setTransform(80,585.8,0.68,0.68,0,0,0,0.1,1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80,572.9,1.13,1.13,0,0,0,0.1,3.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border160x600();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},164).wait(1));

	// PIC
	this.instance_3 = new lib.pic();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,37,1,1,0,0,0,150,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true},164).wait(1));

	// CTA
	this.instance_4 = new lib.HEAD1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(898.5,430,5,5,0,0,0,119.5,27);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1,scaleY:1,x:199.5,y:233},4).to({_off:true},160).wait(1));

	// HEAD
	this.instance_5 = new lib.CTA();
	this.instance_5.parent = this;
	this.instance_5.setTransform(890.5,548,5,5,0,0,0,119.5,40);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(71).to({_off:false},0).to({regY:40.1,scaleX:1.1,scaleY:1.1,x:211.5,y:390.1},4).to({_off:true},89).wait(1));

	// head bkgd
	this.instance_6 = new lib.headbkgd();
	this.instance_6.parent = this;
	this.instance_6.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},164).wait(1));

	// tag
	this.instance_7 = new lib._2016TAGvert();
	this.instance_7.parent = this;
	this.instance_7.setTransform(80.1,536.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo
	this.instance_8 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(272.9,540.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// logo rule
	this.instance_9 = new lib._2016_SCU_logoruleai();
	this.instance_9.parent = this;
	this.instance_9.setTransform(155.6,525.1,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(130).to({_off:false},0).to({_off:true},34).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_10.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({_off:true},164).wait(1));

	// logo box
	this.instance_11 = new lib.box1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},164).wait(1));

	// EHO
	this.instance_12 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(17.1,232.1,0.07,0.07,0,0,0,135,145);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(163).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.5,280,825,865);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;